apiVersion: v1
kind: Namespace
metadata:
  name: ingress-lb
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ingress-nginx
  namespace: ingress-lb
spec:
  repo: https://kubernetes.github.io/ingress-nginx
  chart: ingress-nginx
  targetNamespace: ingress-lb
  valuesContent: |-
    controller:
      service:
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
          service.beta.kubernetes.io/azure-load-balancer-internal: "false"
          service.beta.kubernetes.io/azure-load-balancer-resource-group: yopy-rg
      config:
        use-forwarded-headers: "true"
        compute-full-forwarded-for: "true"
        use-proxy-protocol: "false"
      extraArgs:
        default-ssl-certificate: "ingress-lb/ingress-nginx-tls"
      resources:
        requests:
          cpu: 100m
          memory: 90Mi
        limits:
          cpu: 500m
          memory: 512Mi
      admissionWebhooks:
        enabled: false
      metrics:
        enabled: true
        serviceMonitor:
          enabled: false 